TOPICS: dict[str, list[str]] = {
    "Arrays & Hashing": [
        "contains-duplicate",
        "valid-anagram",
        "two-sum",
        "group-anagrams",
        "top-k-frequent-elements",
        "encode-and-decode-strings",
        "product-of-array-except-self",
        "valid-sudoku",
        "longest-consecutive-sequence",
    ],
    "Two Pointers": [
        "valid-palindrome",
        "two-sum-ii-input-array-is-sorted",
        "3sum",
        "container-with-most-water",
    ],
    "Sliding Window": [
        "best-time-to-buy-and-sell-stock",
        "longest-substring-without-repeating-characters",
        "longest-repeating-character-replacement",
        "permutation-in-string",
    ],
    "Stack": [
        "valid-parentheses",
        "evaluate-reverse-polish-notation",
        "generate-parentheses",
        "daily-temperatures",
        "car-fleet",
    ],
    "Binary Search": [
        "binary-search",
        "search-a-2d-matrix",
        "koko-eating-bananas",
        "find-minimum-in-rotated-sorted-array",
        "search-in-rotated-sorted-array",
    ],
    "Linked List": [
        "reverse-linked-list",
        "merge-two-sorted-lists",
        "reorder-list",
        "remove-nth-node-from-end-of-list",
        "add-two-numbers",
        "find-the-duplicate-number",
    ],
    "Trees": [
        "invert-binary-tree",
        "maximum-depth-of-binary-tree",
        "diameter-of-binary-tree",
        "balanced-binary-tree",
        "same-tree",
        "subtree-of-another-tree",
        "binary-tree-level-order-traversal",
        "binary-tree-right-side-view",
        "count-good-nodes-in-binary-tree",
        "validate-binary-search-tree",
        "kth-smallest-element-in-a-bst",
        "construct-binary-tree-from-preorder-and-inorder-traversal",
    ],
}
